FROM cnes/base-notebook:7a05d6a
#FROM mambaorg/micromamba:latest

RUN mamba clean -a
RUN mamba install  absl-py==2.1.0
RUN mamba install  adal==1.2.7
RUN mamba install  adlfs==2023.10.0
RUN mamba install  aenum==3.1.15
RUN mamba install  affine==2.4.0
RUN mamba install  aiobotocore==2.7.0
RUN mamba install  aiohappyeyeballs==2.4.4
RUN mamba install  aiohttp==3.11.10
RUN mamba install  aioitertools==0.12.0
RUN mamba install  aiosignal==1.3.2
RUN mamba install  alembic==1.14.0
RUN mamba install  annotated-types==0.7.0
RUN mamba install  antlr4-python3-runtime==4.9.3
RUN mamba install  anyio==4.7.0
RUN mamba install  anywidget==0.9.13
RUN mamba install  appdirs==1.4.4
RUN mamba install  argcomplete==3.5.2
RUN mamba install  argon2-cffi==23.1.0
RUN mamba install  argon2-cffi-bindings==21.2.0
RUN mamba install  argopy==0.1.15
RUN mamba install  arro3-compute==0.4.4
RUN mamba install  arro3-core==0.4.4
RUN mamba install  arro3-io==0.4.4
RUN mamba install  arrow==1.3.0
RUN mamba install  asciitree==0.3.3
RUN mamba install  astropy==7.0.0
RUN mamba install  astropy-iers-data==0.2024.12.16.0.35.48
RUN mamba install  asttokens==3.0.0
RUN mamba install  astunparse==1.6.3
RUN mamba install  async_generator==1.10
RUN mamba install  async-lru==2.0.4
RUN mamba install  attrs==24.3.0
RUN mamba install  av==14.0.1
RUN mamba install  awscli==2.22.15
RUN pip install  awscli-plugin-endpoint==0.4
RUN mamba install  awscrt==0.22.0
RUN mamba install  azure-core==1.32.0
RUN mamba install  azure-datalake-store==0.0.51
RUN mamba install  azure-identity==1.17.1
RUN mamba install  azure-storage-blob==12.24.0
RUN mamba install  babel==2.16.0
RUN mamba install  beautifulsoup4==4.12.3
RUN mamba install  black==24.10.0
RUN mamba install  bleach==6.2.0
RUN mamba install  blinker==1.9.0
RUN pip install  blosc==1.11.2
RUN mamba install  bokeh==3.5.2
RUN mamba install  boltons==24.0.0
RUN mamba install  boto3==1.28.64
RUN mamba install  botocore==1.31.64
RUN mamba install  Bottleneck==1.4.2
RUN mamba install  bounded-pool-executor==0.0.3
RUN mamba install  bqplot==0.12.43
RUN mamba install  branca==0.7.2
RUN mamba install  Brotli==1.1.0
RUN mamba install  cached-property==1.5.2
RUN mamba install  cachetools==5.5.0
RUN mamba install  cachey==0.2.1
RUN mamba install  Cartopy==0.24.0
RUN mamba install  cattrs==24.1.2
RUN mamba install  cdsapi==0.7.5
RUN mamba install  certifi==2025.7.9
RUN mamba install  certipy==0.2.1
RUN mamba install  cf_xarray==0.10.0
RUN mamba install  cffi==1.17.1
RUN mamba install  cfgrib==0.9.14.1
RUN mamba install  cftime==1.6.4
RUN mamba install  cgen==2020.1
RUN mamba install  charset-normalizer==3.4.0
RUN pip install  chex==0.1.89
RUN mamba install  ciso==0.2.2
RUN mamba install  click==8.1.7
RUN mamba install  click-plugins==1.1.1
RUN mamba install  cligj==0.7.2
RUN mamba install  cloudpickle==3.1.0
RUN mamba install  cmocean==4.0.3
RUN mamba install  colorama==0.4.6
RUN mamba install  colorcet==3.1.0
RUN mamba install  colorspacious==1.1.2
RUN mamba install  comm==0.2.2
RUN mamba install  configobj==5.0.9
RUN mamba install  contextily==1.6.2
RUN mamba install  contourpy==1.3.1
RUN mamba install  coverage==7.6.9
RUN mamba install  cryptography==40.0.1
RUN mamba install  cycler==0.12.1
RUN mamba install  cytoolz==1.0.1
RUN mamba install  dask==2024.8.0
RUN mamba install  dask-expr==1.1.10
RUN mamba install  dask-gateway==2024.1.0
RUN mamba install  dask-geopandas==0.4.2
RUN mamba install  dask-glm==0.3.2
RUN mamba install  dask_labextension==7.0.0
RUN mamba install  dask-ml==2024.4.4
RUN mamba install  dataclasses==0.8
RUN mamba install  datapi==0.1.1
RUN mamba install  datashader==0.16.3
RUN pip install  DateTime==5.5
RUN mamba install  debugpy==1.8.11
RUN mamba install  decorator==5.1.1
RUN mamba install  defusedxml==0.7.1
RUN mamba install  descartes==1.1.0
RUN mamba install  distributed==2024.8.0
RUN mamba install  distro==1.8.0
RUN mamba install  dnspython==2.6.1
RUN mamba install  docopt-ng==0.9.0
RUN mamba install  docrep==0.3.2
RUN mamba install  docstring_parser==0.16
RUN mamba install  docstring-to-markdown==0.15
RUN mamba install  docutils==0.18.1
RUN mamba install  donfig==0.8.1.post1
RUN mamba install  duckdb==1.1.3
RUN mamba install  earthaccess==0.12.0
RUN mamba install  eccodes==2.37.0
RUN mamba install  ecmwf-api-client==1.6.3
RUN mamba install  efficientnet-pytorch==0.7.1
RUN mamba install  einops==0.8.0
RUN mamba install  email_validator==2.2.0
RUN mamba install  entrypoints==0.4
RUN mamba install  eodag==3.0.1
RUN pip install  eofs==0.0.0
RUN mamba install  erddapy==2.2.3
RUN mamba install  esmpy==8.7.0
RUN mamba install  exceptiongroup==1.2.2
RUN mamba install  executing==2.1.0
RUN mamba install  fastapi==0.115.6
RUN mamba install  fastapi-cli==0.0.7
RUN mamba install  fasteners==0.17.3
RUN mamba install  fastjmd95==0.2.1
RUN mamba install  fastjsonschema==2.21.1
RUN mamba install  fastprogress==1.0.3
RUN mamba install  filelock==3.16.1
RUN mamba install  findlibs==0.0.5
RUN mamba install  fiona==1.10.1
RUN mamba install  flatbuffers==24.3.25
RUN mamba install  flexcache==0.3
RUN mamba install  flexparser==0.4
RUN mamba install  flox==0.9.15
RUN mamba install  folium==0.19.2
RUN mamba install  fonttools==4.55.3
RUN mamba install  fqdn==1.5.1
RUN mamba install  frozenlist==1.5.0
RUN mamba install  fsspec==2023.10.0
RUN mamba install  future==1.0.0
RUN mamba install  gast==0.6.0
RUN mamba install  gcm_filters==0.5.1
RUN mamba install  gcsfs==2023.10.0
RUN mamba install  GDAL==3.9.2
RUN mamba install  geocube==0.7.0
RUN mamba install  geographiclib==2.0
RUN mamba install  geojson==3.1.0
RUN mamba install  geopandas==1.0.1
RUN mamba install  geopy==2.4.1
RUN mamba install  geoviews==1.13.1
RUN mamba install  gh-scoped-creds==4.1
RUN mamba install  gitdb==4.0.11
RUN mamba install  GitPython==3.1.43
RUN mamba install  gmpy2==2.1.5
RUN mamba install  google-api-core==2.24.0
RUN mamba install  google-auth==2.37.0
RUN mamba install  google-auth-oauthlib==1.2.1
RUN mamba install  google-cloud-core==2.4.1
RUN mamba install  google-cloud-storage==2.19.0
RUN mamba install  google-crc32c==1.1.2
RUN mamba install  google-pasta==0.2.0
RUN mamba install  google-resumable-media==2.7.2
RUN mamba install  googleapis-common-protos==1.66.0
RUN mamba install  gpytorch==1.13
RUN mamba install  graphviz==0.20.3
RUN mamba install  greenlet==3.1.1
RUN mamba install  grpcio==1.65.5
RUN mamba install  gsw==3.6.19
RUN mamba install  h11==0.14.0
RUN mamba install  h2==4.1.0
RUN mamba install  h3==4.1.1
RUN mamba install  h5netcdf==1.4.1
RUN mamba install  h5py==3.12.1
RUN mamba install  HeapDict==1.0.1
RUN mamba install  holoviews==1.20.0
RUN mamba install  hpack==4.0.0
RUN mamba install  html5lib==1.1
RUN mamba install  httpcore==1.0.7
RUN mamba install  httplib2==0.22.0
RUN mamba install  httptools==0.6.4
RUN mamba install  httpx==0.28.1
RUN mamba install  huggingface_hub==0.26.5
RUN mamba install  hvplot==0.11.1
RUN mamba install  hydra-core==1.3.2
RUN mamba install  hyperframe==6.0.1
RUN mamba install  idna==3.10
RUN mamba install  imagecodecs==2024.9.22
RUN mamba install  imageio==2.36.1
RUN mamba install  immutabledict==4.2.1
RUN mamba install  importlib_metadata==8.5.0
RUN mamba install  importlib_resources==6.4.5
RUN mamba install  iniconfig==2.0.0
RUN mamba install  intake==2.0.7
RUN mamba install  intake-esm==2023.11.10
RUN mamba install  intake-geopandas==0.4.0
RUN mamba install  intake-stac==0.4.0
RUN mamba install  intake-xarray==2.0.0
RUN mamba install  ipdb==0.13.13
RUN mamba install  ipydatagrid==1.3.2
RUN mamba install  ipykernel==6.29.5
RUN mamba install  ipyleaflet==0.19.2
RUN mamba install  ipympl==0.9.4
RUN mamba install  ipyspin==1.0.1
RUN mamba install  ipython==8.17.2
RUN mamba install  ipython_genutils==0.2.0
RUN mamba install  ipytree==0.2.2
RUN mamba install  ipyurl==0.1.2
RUN mamba install  ipywidgets==8.1.3
RUN mamba install  isodate==0.7.2
RUN mamba install  isoduration==20.11.0
RUN mamba install  jax==0.6.2
RUN mamba install  jaxlib==0.6.2
RUN mamba install  jaxparrow==0.2.3
RUN mamba install  jaxtyping==0.2.19
RUN mamba install  jedi==0.19.2
RUN mamba install  Jinja2==3.1.4
RUN mamba install  jmespath==1.0.1
RUN mamba install  joblib==1.4.2
RUN mamba install  jplephem==2.21
RUN mamba install  json5==0.10.0
RUN mamba install  jsonargparse==4.35.0
RUN mamba install  jsonnet==0.20.0
RUN mamba install  jsonpath-ng==1.5.3
RUN mamba install  jsonpickle==4.0.0
RUN mamba install  jsonpointer==3.0.0
RUN mamba install  jsonschema==4.23.0
RUN mamba install  jsonschema-specifications==2024.10.1
RUN mamba install  jupyter_client==8.6.3
RUN mamba install  jupyter_core==5.7.2
RUN mamba install  jupyter-events==0.10.0
RUN mamba install  jupyter-launcher-shortcuts==4.0.3
RUN mamba install  jupyter-leaflet==0.19.2
RUN mamba install  jupyter-lsp==2.2.5
RUN mamba install  jupyter-panel-proxy==0.1.0
RUN mamba install  jupyter-proxy==0.0.1
RUN mamba install  jupyter-resource-usage==1.1.0
RUN mamba install  jupyter_server==2.14.2
RUN mamba install  jupyter-server-mathjax==0.2.6
RUN mamba install  jupyter_server_proxy==4.3.0
RUN mamba install  jupyter_server_terminals==0.5.3
RUN mamba install  jupyter_server_xarray_leaflet==0.2.3
RUN mamba install  jupyterhub==5.1.0
RUN mamba install  jupyterlab==4.2.4
RUN mamba install  jupyterlab_code_formatter==3.0.2
RUN mamba install  jupyterlab_git==0.50.2
RUN mamba install  jupyterlab-lsp==5.1.0
RUN mamba install  jupyterlab_myst==2.4.2
RUN mamba install  jupyterlab_nvdashboard==0.12.0
RUN mamba install  jupyterlab_pygments==0.3.0
RUN mamba install  jupyterlab_server==2.27.3
RUN mamba install  jupyterlab_widgets==3.0.13
RUN mamba install  keras==3.7.0
RUN mamba install  kerchunk==0.2.7
RUN mamba install  kiwisolver==1.4.7
RUN mamba install  kornia==0.7.4
RUN mamba install  kornia_rs==0.1.7
RUN mamba install  lazy_loader==0.4
RUN mamba install  legacy-cgi==2.6.1
RUN mamba install  lightly==1.5.15
RUN mamba install  lightly-utils==0.0.2
RUN mamba install  lightning==2.4.0
RUN mamba install  lightning-utilities==0.11.9
RUN mamba install  line_profiler==4.1.3
RUN mamba install  linear_operator==0.5.3
RUN mamba install  linkify-it-py==2.0.3
RUN mamba install  llvmlite==0.43.0
RUN mamba install  locket==1.0.0
RUN mamba install  lonboard==0.10.3
RUN mamba install  lsprotocol==2023.0.1
RUN mamba install  lxml==5.3.0
RUN mamba install  lz4==4.3.3
RUN mamba install  Mako==1.3.8
RUN mamba install  mapclassify==2.8.1
RUN mamba install  Markdown==3.6
RUN mamba install  markdown-it-py==3.0.0
RUN mamba install  MarkupSafe==3.0.2
RUN mamba install  matplotlib==3.9.4
RUN mamba install  matplotlib-inline==0.1.7
RUN mamba install  mdit-py-plugins==0.4.2
RUN mamba install  mdurl==0.1.2
RUN mamba install  memory-profiler==0.61.0
RUN mamba install  mercantile==1.2.1
RUN mamba install  MetPy==1.6.3
RUN mamba install  mistune==3.0.2
RUN mamba install  ml_dtypes==0.5.1
RUN mamba install  mock==5.1.0
RUN mamba install  morecantile==6.1.0
RUN mamba install  mpmath==1.3.0
RUN mamba install  msal==1.31.0
RUN mamba install  msal-extensions==1.2.0
RUN mamba install  msgpack==1.1.0
RUN mamba install  multidict==6.1.0
RUN mamba install  multimethod==1.12
RUN mamba install  multipledispatch==0.6.0
RUN mamba install  multiurl==0.3.3
RUN mamba install  munch==4.0.0
RUN mamba install  munkres==1.1.4
RUN mamba install  mypy_extensions==1.0.0
RUN mamba install  namex==0.0.8
RUN mamba install  natsort==8.4.0
RUN mamba install  nb_conda_kernels==2.5.1
RUN mamba install  nbclient==0.10.1
RUN mamba install  nbconvert==7.16.4
RUN mamba install  nbdime==4.0.2
RUN mamba install  nbformat==5.10.4
RUN mamba install  nbgitpuller==1.2.1
RUN mamba install  nbstripout==0.8.1
RUN mamba install  nc-time-axis==1.4.1
RUN mamba install  nest_asyncio==1.6.0
RUN mamba install  netCDF4==1.7.2
RUN mamba install  networkx==3.4.2
RUN mamba install  nose2==0.9.2
RUN mamba install  notebook==7.2.2
RUN mamba install  notebook_shim==0.2.4
RUN mamba install  numba==0.60.0
RUN mamba install  numbagg==0.8.2
RUN mamba install  numcodecs==0.13.1
RUN mamba install  numpy==2.2.6
RUN mamba install  numpy-groupies==0.11.2
RUN mamba install  oauthlib==3.2.2
RUN mamba install  odc-geo==0.4.8
RUN mamba install  odc-stac==0.3.10
RUN mamba install  omegaconf==2.3.0
RUN mamba install  opencv-contrib-python==4.12.0.88
RUN mamba install  opencv-python==4.12.0.88
RUN mamba install  opt_einsum==3.4.0
RUN mamba install  optax==0.2.5
RUN mamba install  optree==0.13.1
RUN mamba install  orjson==3.10.12
RUN mamba install  overrides==7.7.0
RUN mamba install  OWSLib==0.32.0
RUN mamba install  packaging==24.2
RUN mamba install  pamela==1.2.0
RUN mamba install  pandas==2.2.3
RUN mamba install  pandocfilters==1.5.0
RUN mamba install  panel==1.5.4
RUN mamba install  param==2.1.1
RUN mamba install  parcels==3.1.1
RUN mamba install  parso==0.8.4
RUN mamba install  partd==1.4.2
RUN mamba install  pathspec==0.12.1
RUN mamba install  patsy==1.0.1
RUN mamba install  pdal==3.4.5
RUN mamba install  pdal-plugins==1.6.2
RUN mamba install  pexpect==4.9.0
RUN mamba install  pickleshare==0.7.5
RUN mamba install  pillow==11.0.0
RUN mamba install  Pint==0.24.4
RUN mamba install  pint-xarray==0.4
RUN mamba install  pip==24.3.1
RUN mamba install  pkgutil_resolve_name==1.3.10
RUN mamba install  planetary-computer==1.0.0
RUN mamba install  platformdirs==4.3.6
RUN mamba install  plotly==5.24.1
RUN mamba install  pluggy==1.5.0
RUN mamba install  ply==3.11
RUN mamba install  pooch==1.8.2
RUN mamba install  pop-tools==2023.6.0
RUN mamba install  portalocker==2.10.1
RUN mamba install  pqdm==0.2.0
RUN mamba install  pretrainedmodels==0.7.4
RUN mamba install  prometheus_client==0.21.1
RUN mamba install  prompt-toolkit==3.0.38
RUN mamba install  propcache==0.2.1
RUN mamba install  properscoring==0.1
RUN mamba install  proto-plus==1.25.0
RUN mamba install  protobuf==5.27.5
RUN mamba install  psutil==5.9.8
RUN mamba install  psycopg2==2.9.9
RUN mamba install  psygnal==0.11.1
RUN mamba install  ptyprocess==0.7.0
RUN mamba install  pure_eval==0.2.3
RUN mamba install  py2vega==0.6.0
RUN mamba install  pyarrow==15.0.2
RUN mamba install  pyarrow-hotfix==0.6
RUN mamba install  pyasn1==0.6.1
RUN mamba install  pyasn1_modules==0.4.1
RUN mamba install  pycairo==1.27.0
RUN mamba install  pycamhd==0.7.0
RUN mamba install  pycparser==2.22
RUN mamba install  pycryptodome==3.21.0
RUN mamba install  pyct==0.5.0
RUN mamba install  pydantic==2.10.3
RUN mamba install  pydantic_core==2.27.1
RUN mamba install  pydap==3.5
RUN mamba install  pyerfa==2.0.1.5
RUN mamba install  Pygments==2.18.0
RUN mamba install  PyGObject==3.50.0
RUN mamba install  pyinterp==2025.3.0
RUN mamba install  PyJWT==2.10.1
RUN mamba install  pykdtree==1.3.13
RUN mamba install  pymbolic==2024.2.1
RUN mamba install  pynvml==11.5.3
RUN mamba install  pyogrio==0.10.0
RUN mamba install  pyOpenSSL==23.1.1
RUN mamba install  pyorbital==1.9.2
RUN mamba install  pyparsing==3.2.0
RUN mamba install  pyproj==3.7.0
RUN mamba install  PyQt5==5.15.9
RUN mamba install  PyQt5-sip==12.12.2
RUN mamba install  pyresample==1.31.0
RUN mamba install  pyshp==2.3.1
RUN mamba install  PySocks==1.7.1
RUN mamba install  pyspectral==0.13.5
RUN mamba install  pystac==1.11.0
RUN mamba install  pystac-client==0.8.5
RUN mamba install  pytest==8.3.4
RUN mamba install  python-cmr==0.13.0
RUN mamba install  python-dateutil==2.9.0
RUN mamba install  python-dotenv==1.0.1
RUN mamba install  python-geotiepoints==1.7.5
RUN mamba install  python-gist==0.10.6
RUN mamba install  python-gnupg==0.4.9
RUN mamba install  python-json-logger==2.0.7
RUN mamba install  python-lsp-jsonrpc==1.1.2
RUN mamba install  python-lsp-ruff==2.2.2
RUN mamba install  python-lsp-server==1.12.0
RUN mamba install  python-multipart==0.0.19
RUN mamba install  pytools==2024.1.21
RUN mamba install  pytorch-lightning==2.4.0
RUN mamba install  pytz==2024.1
RUN mamba install  pyu2f==0.1.5
RUN mamba install  pyviz_comms==3.0.3
RUN mamba install  PyWavelets==1.8.0
RUN mamba install  PyYAML==6.0.2
RUN mamba install  pyzmq==26.2.0
RUN mamba install  QScintilla==2.14.1
RUN mamba install  rasterio==1.3.11
RUN mamba install  rechunker==0.5.2
RUN mamba install  referencing==0.35.1
RUN mamba install  requests==2.32.3
RUN mamba install  requests-futures==1.0.2
RUN mamba install  requests-oauthlib==2.0.0
RUN mamba install  rfc3339_validator==0.1.4
RUN mamba install  rfc3986-validator==0.1.1
RUN mamba install  rich==13.9.4
RUN mamba install  rich-toolkit==0.11.3
RUN mamba install  rio-cogeo==5.4.0
RUN mamba install  rioxarray==0.17.0
RUN mamba install  roaring-landmask==0.9.1
RUN mamba install  rpds-py==0.22.3
RUN mamba install  rsa==4.9
RUN mamba install  Rtree==1.3.0
RUN mamba install  ruamel.yaml==0.17.17
RUN mamba install  ruamel.yaml.clib==0.2.8
RUN mamba install  ruff==0.8.3
RUN mamba install  s3fs==2023.10.0
RUN mamba install  s3transfer==0.7.0
RUN mamba install  safetensors==0.4.5
RUN mamba install  satpy==0.53.0
RUN mamba install  scikit-image==0.24.0
RUN mamba install  scikit-learn==1.6.0
RUN mamba install  scipy==1.14.1
RUN mamba install  seaborn==0.13.2
RUN mamba install  segmentation_models_pytorch==0.3.4
RUN mamba install  Send2Trash==1.8.3
RUN mamba install  setuptools==75.6.0
RUN mamba install  shapely==2.0.6
RUN mamba install  shellingham==1.5.4
RUN mamba install  simpervisor==1.0.0
RUN mamba install  sip==6.7.12
RUN mamba install  siphash24==1.7
RUN mamba install  six==1.17.0
RUN mamba install  smmap==5.0.0
RUN mamba install  snakeviz==2.2.2
RUN mamba install  sniffio==1.3.1
RUN mamba install  snuggs==1.4.7
RUN mamba install  sortedcontainers==2.4.0
RUN mamba install  soupsieve==2.5
RUN mamba install  sparse==0.15.4
RUN mamba install  SQLAlchemy==2.0.36
RUN mamba install  stack_data==0.6.3
RUN mamba install  stackstac==0.5.1
RUN mamba install  starlette==0.41.3
RUN mamba install  statsmodels==0.14.4
RUN mamba install  stream-zip==0.0.83
RUN mamba install  sympy==1.13.3
RUN mamba install  tblib==3.0.0
RUN mamba install  tenacity==9.0.0
RUN mamba install  tensorboard==2.17.1
RUN mamba install  tensorboard_data_server==0.7.0
RUN mamba install  tensorflow==2.17.0
RUN mamba install  tensorflow_estimator==2.15.0
RUN mamba install  termcolor==2.5.0
RUN mamba install  terminado==0.18.1
RUN mamba install  threadpoolctl==3.5.0
RUN mamba install  tifffile==2024.12.12
RUN mamba install  tiledb==0.31.1
RUN mamba install  timezonefinder==6.5.7
RUN mamba install  timm==0.9.7
RUN mamba install  tinycss2==1.4.0
RUN mamba install  tinynetrc==1.3.1
RUN mamba install  toml==0.10.2
RUN mamba install  tomli==2.2.1
RUN mamba install  toolz==1.0.0
RUN mamba install  torch==2.4.1.post302
RUN mamba install  torchgeo==0.6.1
RUN mamba install  torchmetrics==1.5.2
RUN mamba install  torchvision==0.19.1a0+5ed21bd
RUN mamba install  tornado==6.4.2
RUN mamba install  tqdm==4.67.1
RUN mamba install  traitlets==5.14.3
RUN mamba install  traittypes==0.2.1
RUN mamba install  trajan==0.7.0
RUN mamba install  trollimage==1.26.0
RUN mamba install  trollsift==0.5.3
RUN mamba install  typeguard==4.4.1
RUN mamba install  typer==0.15.1
RUN mamba install  typer-slim==0.15.1
RUN mamba install  types-python-dateutil==2.9.0.20241206
RUN mamba install  typeshed-client==2.4.0
RUN mamba install  typing_extensions==4.12.2
RUN mamba install  typing_utils==0.1.0
RUN mamba install  tzdata==2024.2
RUN mamba install  uc-micro-py==1.0.3
RUN mamba install  ujson==5.10.0
RUN mamba install  unicodedata2==15.1.0
RUN mamba install  uri-template==1.3.0
RUN mamba install  urllib3==1.26.19
RUN mamba install  usgs==0.3.5
RUN mamba install  uvicorn==0.34.0
RUN mamba install  uvloop==0.21.0
RUN mamba install  validators==0.34.0
RUN mamba install  watchfiles==1.0.3
RUN mamba install  watermark==2.5.0
RUN mamba install  wcwidth==0.2.13
RUN mamba install  webcolors==24.11.1
RUN mamba install  webencodings==0.5.1
RUN mamba install  WebOb==1.8.9
RUN mamba install  websocket-client==1.8.0
RUN mamba install  websockets==14.1
RUN mamba install  Werkzeug==3.1.3
RUN mamba install  wheel==0.45.1
RUN mamba install  Whoosh==2.7.4
RUN mamba install  widetrax==1.1.0
RUN mamba install  widgetsnbextension==4.0.13
RUN mamba install  wrapt==1.17.0
RUN mamba install  xarray==2024.11.0
RUN mamba install  xarray-datatree==0.0.14
RUN mamba install  xarray_leaflet==0.2.3
RUN mamba install  xarray-spatial==0.4.0
RUN mamba install  xarrayutils==2.0.1
RUN mamba install  xbatcher==0.4.0
RUN mamba install  xclim==0.53.2
RUN mamba install  xesmf==0.8.8
RUN mamba install  xgboost==2.1.3
RUN mamba install  xgcm==0.8.1
RUN mamba install  xhistogram==0.3.2
RUN mamba install  xmip==0.7.2
RUN mamba install  xmitgcm==0.5.2
RUN mamba install  xpublish==0.3.3
RUN mamba install  xrft==0.0.0
RUN mamba install  xskillscore==0.0.26
RUN mamba install  xvec==0.3.0
RUN mamba install  xxhash==3.5.0
RUN mamba install  xyzservices==2024.9.0
RUN mamba install  yamale==5.2.1
RUN mamba install  yarl==1.18.3
RUN mamba install  zarr==2.18.4
RUN mamba install  zict==3.0.0
RUN mamba install  zipp==3.21.0
RUN mamba install  zope.interface==7.2


